#!/usr/bin/env tsx
/**
 * Copies generated API docs data to the frontend folder.
 * Merges generated wsApiDocsData and restApiDocsData with
 * manually maintained faqData and electrumApiDocsData from the original file.
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const GENERATED_FILE = path.resolve(__dirname, '../../output/frontend/api-docs-data.generated.ts');
const ORIGINAL_FILE = path.resolve(__dirname, '../../../../frontend/src/app/docs/api-docs/api-docs-data.ts');
const OUTPUT_FILE = path.resolve(__dirname, '../../../../frontend/src/app/docs/api-docs/api-docs-data.generated.ts');

async function extractFaqAndElectrumData(content: string): Promise<{ faqData: string; electrumApiDocsData: string }> {
  // Extract faqData
  const faqMatch = content.match(/export const faqData = (\[[\s\S]*?\n\]);/);
  const faqData = faqMatch ? faqMatch[1] : '[]';

  // Extract electrumApiDocsData
  const electrumMatch = content.match(/export const electrumApiDocsData = (\[[\s\S]*?\n\]);/);
  const electrumApiDocsData = electrumMatch ? electrumMatch[1] : '[]';

  return { faqData, electrumApiDocsData };
}

async function main() {
  try {
    // Check if generated file exists
    try {
      await fs.access(GENERATED_FILE);
    } catch {
      console.error('Generated file not found. Run "npm run generate:frontend" first.');
      process.exit(1);
    }

    // Read generated file
    const generatedContent = await fs.readFile(GENERATED_FILE, 'utf-8');

    // Extract wsApiDocsData and restApiDocsData from generated file
    const wsMatch = generatedContent.match(/export const wsApiDocsData = (\[[\s\S]*?\n\]);/);
    const restMatch = generatedContent.match(/export const restApiDocsData = (\[[\s\S]*?\n\]);/);

    if (!wsMatch || !restMatch) {
      console.error('Could not extract wsApiDocsData or restApiDocsData from generated file.');
      process.exit(1);
    }

    const wsApiDocsData = wsMatch[1];
    const restApiDocsData = restMatch[1];

    // Read original file and extract faqData and electrumApiDocsData
    let faqData = '[]';
    let electrumApiDocsData = '[]';

    try {
      const originalContent = await fs.readFile(ORIGINAL_FILE, 'utf-8');
      const extracted = await extractFaqAndElectrumData(originalContent);
      faqData = extracted.faqData;
      electrumApiDocsData = extracted.electrumApiDocsData;
    } catch {
      console.warn('Could not read original file, using empty arrays for faqData and electrumApiDocsData');
    }

    // Generate combined output
    const output = `// AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
// Generated by api-spec-generator
// Run 'npm run generate:frontend && npm run copy:frontend' in tools/api-spec-generator to regenerate
//
// This file contains:
// - wsApiDocsData: Generated from backend WebSocket handler
// - restApiDocsData: Generated from backend route files
// - faqData: Preserved from original api-docs-data.ts
// - electrumApiDocsData: Preserved from original api-docs-data.ts

const bitcoinNetworks = ['', 'testnet', 'testnet4', 'signet'];
const liquidNetworks = ['liquid', 'liquidtestnet'];
const lightningNetworks = ['', 'testnet', 'signet'];

const showJsExamplesDefault = { '': true, 'testnet': true, 'signet': true, 'liquid': true, 'liquidtestnet': false };
const showJsExamplesDefaultFalse = { '': false, 'testnet': false, 'signet': false, 'liquid': false, 'liquidtestnet': false };

export const wsApiDocsData = ${wsApiDocsData};

export const restApiDocsData = ${restApiDocsData};

export const faqData = ${faqData};

export const electrumApiDocsData = ${electrumApiDocsData};
`;

    // Write output file
    await fs.writeFile(OUTPUT_FILE, output, 'utf-8');
    console.log(`Successfully wrote ${OUTPUT_FILE}`);
    console.log('\nTo use the generated data, update the import in api-docs.component.ts:');
    console.log("  import { faqData, restApiDocsData, wsApiDocsData, electrumApiDocsData } from '@app/docs/api-docs/api-docs-data.generated';");

  } catch (error) {
    console.error('Error:', error);
    process.exit(1);
  }
}

main();
