name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
        os: ["ubuntu-latest"]
        browser: [chrome]
    name: E2E tests on ${{ matrix.browser }} - ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.browser }} browser tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: frontend
          build: npm run config:defaults
          start: npm run start:local-prod
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 120
          record: true
          parallel: true
          group: Tests on ${{ matrix.browser }}
          browser: ${{ matrix.browser }}
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
