name: Docker build for testing
env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build and run
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Checkout project
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2

      - name: Init repo for Dockerization
        run: docker/init.sh "$SHORT_SHA"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # v1
        id: buildx

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Cache Docker layers
        uses: actions/cache@661fd3eb7f2f20d8c7c84bc2b0509efd7a826628 # v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker buildx for frontend against hash
        run: |
          docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache-new" \
          --platform linux/amd64 \
          --tag ${{ secrets.DOCKER_HUB_USER }}/frontend:$SHORT_SHA \
          --tag ${{ secrets.DOCKER_HUB_USER }}/frontend:latest \
          --output "type=docker,dest=/tmp/frontend.tar" ./frontend/ \
          --build-arg commitHash=$SHORT_SHA

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: /tmp/frontend.tar

      - name: List folder
        run: |
          ls -lasFR /tmp/frontend.tar

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  use-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx for testing
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: /tmp

      - name: List folder
        run: |
          ls -lasFR /tmp/frontend.tar

      - name: Load image
        run: |
          docker load --input /tmp/frontend.tar
          docker image ls -a
          docker image inspect ${{ secrets.DOCKER_HUB_USER }}/frontend:latest

      - name: Start frontend
        run: |
          docker run -d -p 81:80 --name frontend ${{ secrets.DOCKER_HUB_USER }}/frontend:latest

      - name: Check frontend is running
        run: |
          docker ps

      - name: Sleep for 35 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "35s"

      - name: Check frontend is running 2
        run: |
          docker ps

      - name: Check logs
        run: |
          docker logs frontend

      - name: List remote files
        run: |
          docker exec -it frontend ls -R /var/www/

      - name: curl
        run: |
          curl -vvv http://localhost:81/
