name: Docker build for testing
env:
  DOCKER_CLI_EXPERIMENTAL: enabled
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0

on:
  push:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        service:
          - frontend
          #- backend
    runs-on: ubuntu-18.04
    name: Build and run
    steps:
      # - name: Set env variables
      # run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      # - name: Show set environment variables
      # run: |
      # printf "      TAG: %s\n"  "$TAG"

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: Checkout project
        uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2

      - name: Init repo for Dockerization
        run: docker/init.sh "$SHORT_SHA"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480 # v1
        id: qemu

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25 # v1
        id: buildx

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Cache Docker layers
        uses: actions/cache@661fd3eb7f2f20d8c7c84bc2b0509efd7a826628 # v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker buildx for ${{ matrix.service }} against hash
        run: |
          docker buildx build \
          --cache-from "type=local,src=/tmp/.buildx-cache" \
          --cache-to "type=local,dest=/tmp/.buildx-cache" \
          --platform linux/amd64 \
          --tag ${{ secrets.DOCKER_HUB_USER }}/${{ matrix.service }}:$SHORT_SHA \
          --tag ${{ secrets.DOCKER_HUB_USER }}/${{ matrix.service }}:latest \
          --output "type=docker,dest=/tmp/${{ matrix.service }}.tar" ./${{ matrix.service }}/ \
          --build-arg commitHash=$SHORT_SHA

      # - name: Build
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     load: true
      #     tags: ${{ secrets.DOCKER_HUB_USER }}/${{ matrix.service }}:latest

      # - name: Inspect
      #   run: |
      #     docker image inspect ${{ secrets.DOCKER_HUB_USER }}/${{ matrix.service }}:latest

      - name: Upload image
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.service }}
          path: /tmp/${{ matrix.service }}.tar

  use-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Docker Buildx for testing
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/frontend.tar
          docker image ls -a
          docker image inspect ${{ secrets.DOCKER_HUB_USER }}/frontend:latest

      - name: Start frontend
        run: |
          docker run ${{ secrets.DOCKER_HUB_USER }}/frontend:latest
