on:
  workflow_dispatch:
  inputs:
    version:
      description: 'Image Version'
      required: true
      default: 'latest'
      type: 
jobs:
  print-images-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: digest
      - name: Run script
        working-directory: digest
        - run: |
            sh ./docker/scripts/get_image_digest.sh $VERSION
          env: 
            VERSION: ${{ inputs.version }}
