name: Node Compatibility Test

on: 
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: echo "::set-output name=version_matrix::$(curl https://endoflife.date/api/nodejs.json | jq -c '[.[] | select(.eol > (now | strftime("%Y-%m-%d"))) | .cycle]')"
    outputs:
      version_matrix: ${{ steps.set-matrix.outputs.version_matrix }}
  ci:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.build-matrix.outputs.version_matrix) }}
    steps:
    - name: Clone Repository (Latest)
      uses: actions/checkout@v2
      if: github.event.inputs.git-ref == ''
      
    - name: Clone Repository (Custom Ref)
      uses: actions/checkout@v2
      if: github.event.inputs.git-ref != ''
      with:
        ref: ${{ github.event.inputs.git-ref }}
    
    - name: setup node ${{ matrix.version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.version }}

    - name: show node version
      if: always()
      run: node --version
    
    - name: show npm version
      if: always()
      run: npm --version

    - name: install frontend dependencies
      if: always() 
      working-directory: frontend
      run: npm install

    - name: run frontend build
      if: always() 
      working-directory: frontend
      run: npm run build

    - name: install backend dependencies
      if: always() 
      working-directory: backend
      run: npm install

    - name: run backend build
      if: always() 
      working-directory: backend
      run: npm run build
